CREATE TABLE epicUser
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255),
    name       VARCHAR(255),
    avatar_url VARCHAR(255),
    CONSTRAINT pk_epicUser PRIMARY KEY (id)
);

ALTER TABLE epicUser
    ADD CONSTRAINT uc_epicUser_email UNIQUE (email);